### ISSUE TITLE
Submit link back to cc65 wiki

### ISSUE THREAD

**Issue by xandark** [jeremysrand/a2sudoku#1]
Hello! This is great! 

How about adding a link to this project to the cc65 wiki of projects that are made using cc65?:

   https://github.com/cc65/wiki/wiki/Applications-written-in-C-or-C-with-assembler

**Comment by jeremysrand** [comment]
I would like to but I don't quite see how I can do that short of asking someone on the cc65 project to add it for me.  It seems that github does not support pull requests for wiki pages and the cc65 project does not allow me to edit the wiki page directly.

**Comment by polluks** [comment]
done :-)

**Comment by jeremysrand** [comment]
Thanks!
